services:
  - type: web
    name: lavalust-products
    runtime: docker
    plan: free
    healthCheckPath: /index.php
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "13226"
      - key: DB_SSL_MODE
        value: required
      - key: DB_SSL_CIPHER
        value: AES256-SHA
      - key: DB_NAME
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false